### ISSUE TITLE
BuildVars - explanation

### ISSUE THREAD

**Issue by Clevero** [rubenlagus/TelegramBotsExample#18]
Try to start a simple Echo Bot.

But I have some problems with settings in BuildVars.java

For what is EXTERNALWEBHOOKURL and INTERNALWEBHOOKURL?

Can those be set to my domain/ip of my server?

**Comment by rubenlagus** [comment]
Those two fields are used only in case you want to use a Webook bot. 
1. **EXTERNALWEBHOOKURL**: Is the external address of your server, like _https://mydomain.com
2. **INTERNALWEBHOOKURL**: Is the url where the rest client will be listening to (added to support inverse proxies), for example _http:127.0.0.1_

Remember that webhook bots requires that the server have a valid ssl certificate (self-signed or not) in order to work correctly and that the CN of the certificate must exactly match your domain.

**Comment by Clevero** [comment]
thanks! :+1:
